# output   
# The line1 was there in the autogenerated code but it is not required, rest all is perfect.


import os            
import shutil         #used to copying archived files and folders on our file system
from datetime import datetime, timedelta      #used to calculate if files are older than 30 days

# set the path of the folder to check
#First it sets path to Downloads foler in user's home directory('~')-->(user's home directory shortcut) which is basically good if i dont want to provide the whole path
folder_path = os.path.join(os.path.expanduser('~'), 'Downloads') 

# set the path of the folder to move files to a new directory called "to_delete"
to_delete_folder_path = os.path.join(os.path.expanduser('~'), 'to_delete')

# create the folder if it doesn't exist---checks if the to_delete folder already exists(using os module)--if not it creates one using os module
if not os.path.exists(to_delete_folder_path):
    os.makedirs(to_delete_folder_path)              #makedirs makes a directory

# get the list of files in the folder--going through the list of files in the downloads folder and saves them in the files variable
files = os.listdir(folder_path)

# get the current date
now = datetime.now()

# loop through the files
for file in files:
    # get the file path
    file_path = os.path.join(folder_path, file)

    # get the file's modification date
    modified_date = datetime.fromtimestamp(os.path.getmtime(file_path))

    # calculate the time difference
    time_difference = now - modified_date

    # if the file is older than 30 days, move it
    if time_difference > timedelta(days=30):
        shutil.move(file_path, to_delete_folder_path)

#This is an auto-generated script
#I will make changes to it (if required) and run that final correct python script to automate my task of cleaning downloads folder.
#So, this autogenerated code is good as i only need to remove the line1 except that everything else looks great
#The autogenerated code also has comments which is great.